setTimeout(()=>{
    console.log("Request-R1");
},10000)
setTimeout(()=>{
    console.log("Request-R2");
},5000)
setTimeout(()=>{
    console.log("Request-R3");
},3000)
setTimeout(()=>{
    console.log("Request-R4");
},1000)